In [1]:
import numpy as np
import pandas as pd

In [14]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv("covid_toy.csv")

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df.isnull().sum() # fever has 10 missing values so we have to fix it

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

In [12]:
X_train

    age  gender  fever   cough       city
96   51  Female  101.0  Strong    Kolkata
20   12    Male   98.0  Strong  Bangalore
23   80  Female   98.0    Mild      Delhi
86   25    Male  104.0    Mild  Bangalore
41   82    Male    NaN    Mild    Kolkata
..  ...     ...    ...     ...        ...
28   16    Male  104.0    Mild    Kolkata
40   49  Female  102.0    Mild      Delhi
92   82  Female  102.0  Strong    Kolkata
88    5  Female  100.0    Mild    Kolkata
95   12  Female  104.0    Mild  Bangalore

[80 rows x 5 columns]

<h1>Mushkil ZindGi</h1>

In [16]:
# adding simple Imputer to fever column

si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[["fever"]])

X_test_fever = si.transform(X_test[["fever"]])

In [17]:
X_train_fever.shape

(80, 1)

In [18]:
X_test_fever.shape

(20, 1)

In [20]:
oe = OrdinalEncoder(categories=[["Mild","Strong"]])

X_train_cough = oe.fit_transform(X_train[["cough"]])

X_test_cough = oe.transform(X_test[["cough"]])

In [22]:
X_train_cough.shape

(80, 1)

In [24]:
X_test_cough.shape

(20, 1)

In [26]:
one = OneHotEncoder(drop="first",sparse_output=False)

X_train_gender_city = one.fit_transform(X_train[["gender","city"]])

X_test_gender_city = one.transform(X_test[["gender","city"]])

In [28]:
X_train_gender_city.shape

(80, 4)

In [29]:
X_test_gender_city.shape

(20, 4)

In [30]:
X_train_Age = X_train.drop(columns=["gender","fever","cough","city"]).values

X_test_Age = X_test.drop(columns=["gender","fever","cough","city"]).values

In [32]:
X_train_Age.shape

(80, 1)

In [33]:
X_train_transformed = np.concatenate((X_train_Age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

X_test_transformed = np.concatenate((X_test_Age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

In [35]:
X_train_transformed.shape

(80, 7)

<h1>Mentors Zindgi</h1>

In [40]:
from sklearn.compose import ColumnTransformer

transformer = ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["fever"]),
    ("tnf2",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ("tnf3",OneHotEncoder(drop="first",sparse_output=False),["gender","city"])
],remainder="passthrough")

In [42]:
transformer.fit_transform(X_train).shape

(80, 7)