<h1>Getting first Page API Data Of Movie</h1>

In [1]:
import pandas as pd
import requests

In [4]:
response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=4c30f5936a227aca46fd15ffa436045c&language=en-US&page=1%27")

In [14]:
df = pd.DataFrame(response.json()["results"])[["id","title","overview","release_date","popularity","vote_average","vote_count"]]

In [16]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,126.5761,8.956,1826
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,110.5352,8.723,30649
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,321.7840,8.709,3158
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,129.8917,8.692,5483
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,40.9483,8.687,23089

In [19]:
df = pd.DataFrame()

In [20]:
df

Empty DataFrame
Columns: []
Index: []

<h1>Loop through the 549 Pages and append them into the dataframe by ignoring the index</h1>

In [ ]:
for i in range(1,550):
    response = requests.get(f"https://api.themoviedb.org/3/movie/top_rated?api_key=4c30f5936a227aca46fd15ffa436045c&language=en-US&page={i}")
    temp_df = pd.DataFrame(response.json()["results"])[["id","title","overview","release_date","popularity","vote_average","vote_count"]]
    df = pd.concat([df,temp_df],ignore_index=True)

In [26]:
df.to_csv("movies.csv") #then save them to the csv as df