<h1>Working With JSON Data</h1>

In [13]:
import pandas as pd

pd.read_json("recipe.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

<h1>Working with SQL Data</h1>

In [14]:
!pip install mysql.connecter

ERROR: Could not find a version that satisfies the requirement mysql.connecter (from versions: none)
ERROR: No matching distribution found for mysql.connecter

In [15]:
!pip install mysql.connectore

ERROR: Could not find a version that satisfies the requirement mysql.connectore (from versions: none)
ERROR: No matching distribution found for mysql.connectore

In [16]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 300.5 kB/s  0:01:39[31m291.9 kB/s eta 0:00:02
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-linux_x86_64.whl size=248042 sha256=0b2aa5c6092ce1d037f2af0d7a97e0b6bed4b9254db111b3cfb88433ca099577
  Stored in directory: /home/malikahmadrasheed/.cache/pip/wheels/4e/c1/23/9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

In [17]:
import mysql.connector

In [21]:
conn = mysql.connector.connect(host="localhost",user="root",password="",database="world")

In [28]:
df = pd.read_sql_query("SELECT * FROM countrylanguage WHERE isOfficial LIKE 'T' ",conn)

/tmp/ipykernel_5687/2123587503.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM countrylanguage WHERE isOfficial LIKE 'T' ",conn)

In [29]:
df

    CountryCode   Language IsOfficial  Percentage
0           ABW      Dutch          T         5.3
1           AFG       Dari          T        32.1
2           AFG     Pashto          T        52.4
3           AIA    English          T         0.0
4           ALB  Albaniana          T        97.9
..          ...        ...        ...         ...
233         ZAF  Afrikaans          T        14.3
234         ZAF    English          T         8.5
235         ZAF      Xhosa          T        17.7
236         ZAF       Zulu          T        22.7
237         ZWE    English          T         2.2

[238 rows x 4 columns]

In [34]:
pd.read_sql_query("SELECT * FROM country WHERE Continent = 'Africa' AND GovernmentForm = 'Republic' ",conn)

/tmp/ipykernel_5687/3590534207.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE Continent = 'Africa' AND GovernmentForm = 'Republic' ",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,AGO,Angola,Africa,Central Africa,1246700.0,1975,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56,AO
1,BDI,Burundi,Africa,Eastern Africa,27834.0,1962,6695000,46.2,903.0,982.0,Burundi/Uburundi,Republic,Pierre Buyoya,552,BI
2,BEN,Benin,Africa,Western Africa,112622.0,1960,6097000,50.2,2357.0,2141.0,Bénin,Republic,Mathieu Kérékou,187,BJ
3,BFA,Burkina Faso,Africa,Western Africa,274000.0,1960,11937000,46.7,2425.0,2201.0,Burkina Faso,Republic,Blaise Compaoré,549,BF
4,BWA,Botswana,Africa,Southern Africa,581730.0,1966,1622000,39.3,4834.0,4935.0,Botswana,Republic,Festus G. Mogae,204,BW
5,CAF,Central African Republic,Africa,Central Africa,622984.0,1960,3615000,44.0,1054.0,993.0,Centrafrique/Bê-Afrîka,Republic,Ange-Félix Patassé,1889,CF
6,CIV,Côte d’Ivoire,Africa,Western Africa,322463.0,1960,14786000,45.2,11345.0,10285.0,Côte d’Ivoire,Republic,Laurent Gbagbo,2814,CI
7,CMR,Cameroon,Africa,Central Africa,475442.0,1960,15085000,54.8,9174.0,8596.0,Cameroun/Cameroon,Republic,Paul Biya,1804,CM
8,COD,"Congo, The Democratic Republic of the",Africa,Central Africa,2344858.0,1960,51654000,48.8,6964.0,2474.0,République Démocratique du Congo,Republic,Joseph Kabila,2298,CD
9,COG,Congo,Africa,Central Africa,342000.0,1960,2943000,47.4,2108.0,2287.0,Congo,Republic,Denis Sassou-Nguesso,2296,CG
10,COM,Comoros,Africa,Eastern Africa,1862.0,1975,578000,60.0,4401.0,4361.0,Komori/Comores,Republic,Azali Assoumani,2295,KM
11,CPV,Cape Verde,Africa,Western Africa,4033.0,1975,428000,68.9,435.0,420.0,Cabo Verde,Republic,António Mascarenhas Monteiro,1859,CV
12,DJI,Djibouti,Africa,Eastern Africa,23200.0,1977,638000,50.8,382.0,373.0,Djibouti/Jibuti,Republic,Ismail Omar Guelleh,585,DJ
13,DZA,Algeria,Africa,Northern Africa,2381741.0,1962,31471000,69.7,49982.0,46966.0,Al-Jaza’ir/Algérie,Republic,Abdelaziz Bouteflika,35,DZ
14,EGY,Egypt,Africa,Northern Africa,1001449.0,1922,68470000,63.3,82710.0,75617.0,Misr,Republic,Hosni Mubarak,608,EG
15,ERI,Eritrea,Africa,Eastern Africa,117600.0,1993,3850000,55.8,650.0,755.0,Ertra,Republic,Isayas Afewerki [Isaias Afwerki],652,ER
16,ETH,Ethiopia,Africa,Eastern Africa,1104300.0,-1000,62565000,45.2,6353.0,6180.0,YeItyop´iya,Republic,Negasso Gidada,756,ET
17,GAB,Gabon,Africa,Central Africa,267668.0,1960,1226000,50.1,5493.0,5279.0,Le Gabon,Republic,Omar Bongo,902,GA
18,GHA,Ghana,Africa,Western Africa,238533.0,1957,20212000,57.4,7137.0,6884.0,Ghana,Republic,John Kufuor,910,GH
19,GIN,Guinea,Africa,Western Africa,245857.0,1958,7430000,45.6,2352.0,2383.0,Guinée,Republic,Lansana Conté,926,GN
20,GMB,Gambia,Africa,Western Africa,11295.0,1965,1305000,53.2,320.0,325.0,The Gambia,Republic,Yahya Jammeh,904,GM
21,GNB,Guinea-Bissau,Africa,Western Africa,36125.0,1974,1213000,49.0,293.0,272.0,Guiné-Bissau,Republic,Kumba Ialá,927,GW
22,GNQ,Equatorial Guinea,Africa,Central Africa,28051.0,1968,453000,53.6,283.0,542.0,Guinea Ecuatorial,Republic,Teodoro Obiang Nguema Mbasogo,2972,GQ
23,KEN,Kenya,Africa,Eastern Africa,580367.0,1963,30080000,48.0,9217.0,10241.0,Kenya,Republic,Daniel arap Moi,1881,KE
24,LBR,Liberia,Africa,Western Africa,111369.0,1847,3154000,51.0,2012.0,NaN,Liberia,Republic,Charles Taylor,2440,LR
25,MLI,Mali,Africa,Western Africa,1240192.0,1960,11234000,46.7,2642.0,2453.0,Mali,Republic,Alpha Oumar Konaré,2482,ML
26,MOZ,Mozambique,Africa,Eastern Africa,801590.0,1975,19680000,37.5,2891.0,2711.0,Moçambique,Republic,Joaquím A. Chissano,2698,MZ
27,MRT,Mauritania,Africa,Western Africa,1025520.0,1960,2670000,50.8,998.0,1081.0,Muritaniya/Mauritanie,Republic,Maaouiya Ould Sid´Ahmad Taya,2509,MR
28,MUS,Mauritius,Africa,Eastern Africa,2040.0,1968,1158000,71.0,4251.0,4186.0,Mauritius,Republic,Cassam Uteem,2511,MU
29,MWI,Malawi,Africa,Eastern Africa,118484.0,1964,10925000,37.6,1687.0,2527.0,Malawi,Republic,Bakili Muluzi,2462,MW
30,NAM,Namibia,Africa,Southern Africa,824292.0,1990,1726000,42.5,3101.0,3384.0,Namibia,Republic,Sam Nujoma,2726,NA
31,NER,Niger,Africa,Western Africa,1267000.0,1960,10730000,41.3,1706.0,1580.0,Niger,Republic,Mamadou Tandja,2738,NE
32,RWA,Rwanda,Africa,Eastern Africa,26338.0,1962,7733000,39.3,2036.0,1863.0,Rwanda/Urwanda,Republic,Paul Kagame,3047,RW
33,SEN,Senegal,Africa,Western Africa,196722.0,1960,9481000,62.2,4787.0,4542.0,Sénégal/Sounougal,Republic,Abdoulaye Wade,3198,SN
34,SLE,Sierra Leone,Africa,Western Africa,71740.0,1961,4854000,45.3,746.0,858.0,Sierra Leone,Republic,Ahmed Tejan Kabbah,3207,SL
35,SOM,Somalia,Africa,Eastern Africa,637657.0,1960,10097000,46.2,935.0,NaN,Soomaaliya,Republic,Abdiqassim Salad Hassan,3214,SO
36,STP,Sao Tome and Principe,Africa,Central Africa,964.0,1975,147000,65.3,6.0,NaN,São Tomé e Príncipe,Republic,Miguel Trovoada,3172,ST
37,SYC,Seychelles,Africa,Eastern Africa,455.0,1976,77000,70.4,536.0,539.0,Sesel/Seychelles,Republic,France-Albert René,3206,SC
38,TCD,Chad,Africa,Central Africa,1284000.0,1960,7651000,50.5,1208.0,1102.0,Tchad/Tshad,Republic,Idriss Déby,3337,TD
39,TGO,Togo,Africa,Western Africa,56785.0,1960,4629000,54.7,1449.0,1400.0,Togo,Republic,Gnassingbé Eyadéma,3332,TG
40,TUN,Tunisia,Africa,Northern Africa,163610.0,1956,9586000,73.7,20026.0,18898.0,Tunis/Tunisie,Republic,Zine al-Abidine Ben Ali,3349,TN
41,TZA,Tanzania,Africa,Eastern Africa,883749.0,1961,33517000,52.3,8005.0,7388.0,Tanzania,Republic,Benjamin William Mkapa,3306,TZ
42,UGA,Uganda,Africa,Eastern Africa,241038.0,1962,21778000,42.9,6313.0,6887.0,Uganda,Republic,Yoweri Museveni,3425,UG
43,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716,ZA
44,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162,ZM
45,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068,ZW