In [58]:
import pandas as pd
import numpy as np

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [59]:
df = pd.read_csv("train2.csv")[['Age','Pclass','SibSp','Parch','Survived']]

In [42]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [60]:
df.dropna(inplace=True)

In [5]:
df.isnull().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [61]:
x = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [7]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [62]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring="accuracy",cv=20))

np.float64(0.6933333333333332)

<h1>Feature Construction</h1>

In [63]:
x["Family_size"] = x["SibSp"] + x["Parch"] + 1

In [64]:
x.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [65]:
def family(num):
    if num == 0:
        return 0 #alone
    elif num > 1 and num <=4:
        return 1 # means small family
    else:
        return 2 # large family

In [56]:
family(5)

2

In [66]:
x["FamilyType"] = x["Family_size"].apply(family)

In [50]:
x.sample(20)

      Age  Pclass  SibSp  Parch  Family_size  FamilyType
385  18.0       2      0      0            1           1
248  37.0       1      1      1            3           1
811  39.0       3      0      0            1           1
35   42.0       1      1      0            2           1
153  40.5       3      0      2            3           1
774  54.0       2      1      3            5           2
836  21.0       3      0      0            1           1
801  31.0       2      1      1            3           1
532  17.0       3      1      1            3           1
437  24.0       2      2      3            6           2
551  27.0       2      0      0            1           1
806  39.0       1      0      0            1           1
636  32.0       3      0      0            1           1
719  33.0       3      0      0            1           1
518  36.0       2      1      0            2           1
3    35.0       1      1      0            2           1
829  62.0       1      0      0            1           1
23   28.0       1      0      0            1           1
192  19.0       3      1      0            2           1
870  26.0       3      0      0            1           1

In [67]:
x.drop(columns=["SibSp","Parch","Family_size"],inplace=True)

In [69]:
x.head(10)

     Age  Pclass  FamilyType
0   22.0       3           1
1   38.0       1           1
2   26.0       3           2
3   35.0       1           1
4   35.0       3           2
6   54.0       1           2
7    2.0       3           2
8   27.0       3           1
9   14.0       2           1
10   4.0       3           1

In [70]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=20))

np.float64(0.7326587301587301)

<h1>Feature Spliting</h1>

In [71]:
df = pd.read_csv("train2.csv")

In [72]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [73]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [79]:
df["Title"] = df["Name"].str.split(",",expand=True)[1].str.split(".",expand=True)[0]

In [82]:
df[["Title","Name"]]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [85]:
(df.groupby('Title').mean()['Survived']).sort_values(ascending=False)

TypeError: agg function failed [how->mean,dtype->object]