In [20]:
import pandas as pd
import numpy as np

from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [2]:
df = pd.read_csv("/Advertising Budget and Sales.csv")

In [3]:
df.head()

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               200 non-null    int64
 1   TV Ad Budget ($)         200 non-null    float64
 2   Radio Ad Budget ($)      200 non-null    float64
 3   Newspaper Ad Budget ($)  200 non-null    float64
 4   Sales ($)                200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [6]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [7]:
df.head()

   TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)  Sales ($)
0             230.1                 37.8                     69.2       22.1
1              44.5                 39.3                     45.1       10.4
2              17.2                 45.9                     69.3        9.3
3             151.5                 41.3                     58.5       18.5
4             180.8                 10.8                     58.4       12.9

In [8]:
# Sales=β0​+β1​(TV)+β2​(Radio)+β3​(Newspaper) in simple linear reg we have some thing y = Bo+B1X
# and the sheet we create is called regression plane not reg line in multiple linear reg

df.describe()

,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
count,200.000000,200.000000,200.000000,200.000000
mean,147.042500,23.264000,30.554000,14.022500
std,85.854236,14.846809,21.778621,5.217457
min,0.700000,0.000000,0.300000,1.600000
25%,74.375000,9.975000,12.750000,10.375000
50%,149.750000,22.900000,25.750000,12.900000
75%,218.825000,36.525000,45.100000,17.400000
max,296.400000,49.600000,114.000000,27.000000

In [12]:
x = df.iloc[:,0:3]
y = df.iloc[:,-1]

In [13]:
x

     TV Ad Budget ($)  Radio Ad Budget ($)  Newspaper Ad Budget ($)
0               230.1                 37.8                     69.2
1                44.5                 39.3                     45.1
2                17.2                 45.9                     69.3
3               151.5                 41.3                     58.5
4               180.8                 10.8                     58.4
..                ...                  ...                      ...
195              38.2                  3.7                     13.8
196              94.2                  4.9                      8.1
197             177.0                  9.3                      6.4
198             283.6                 42.0                     66.2
199             232.1                  8.6                      8.7

[200 rows x 3 columns]

In [14]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales ($), Length: 200, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [17]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)

LinearRegression()

In [18]:
y_pred =lr.predict(X_test)

In [19]:
y_pred

array([14.0533655 ,  9.3596964 ,  6.84168105, 15.57542062, 18.24566528,
       15.69705683,  7.30213681, 20.55741282, 12.91982687, 17.56977582,
       10.56954425, 19.44183679,  9.02152837, 10.39883137, 14.23578821,
       12.14385282,  8.89722911, 17.65602288, 16.59817803, 18.63325138,
       16.91499972, 16.20074839, 11.56907383, 11.79479752, 15.14324825,
       12.31833158, 15.39070301,  7.93709454, 16.78291467, 14.14997697,
       16.66592168, 16.81179836, 13.06481745, 12.90749021,  8.53383456,
       10.87895886, 21.98983006, 20.14333152, 16.31534821, 19.97848869])

In [22]:
print("MSE" ,mean_squared_error(y_test,y_pred))
print("MAE" ,mean_absolute_error(y_test,y_pred))
print("r2 Score" ,r2_score(y_test,y_pred))
print("RMSE" ,np.sqrt(mean_squared_error(y_test,y_pred)))

MSE 4.503125945046122
MAE 1.6462745449078695
r2 Score 0.7575894500772721
RMSE 2.1220570079632926

In [ ]:
# so Root mean squared error tell us that our model is 2.12 sales units away from the true value.

In [23]:
import plotly.express as px
import plotly.graph_objects as go

In [30]:
# Regression plane visualization for Tv ad column or radio one

# Create grid
x_tv = np.linspace(df['TV Ad Budget ($)'].min(), df['TV Ad Budget ($)'].max(), 30)
x_radio = np.linspace(df['Radio Ad Budget ($)'].min(), df['Radio Ad Budget ($)'].max(), 30)

xGrid_tv, xGrid_radio = np.meshgrid(x_tv, x_radio)

# Calculate the mean of 'Newspaper Ad Budget ($)' to keep it constant for the 3D plane visualization
mean_newspaper = df['Newspaper Ad Budget ($)'].mean()

# Create a constant array for 'Newspaper Ad Budget ($)' with the mean value
xGrid_newspaper = np.full(xGrid_tv.shape, mean_newspaper)

# Combine the grids into a single array for prediction
final = np.vstack((xGrid_tv.ravel(), xGrid_radio.ravel(), xGrid_newspaper.ravel())).T

z = lr.predict(final).reshape(30, 30)

# 3D Plot
fig = px.scatter_3d(
    df,
    x='TV Ad Budget ($)',
    y='Radio Ad Budget ($)',
    z='Sales ($)',
    opacity=0.8
)

fig.add_trace(
    go.Surface(
        x=x_tv,
        y=x_radio,
        z=z,
        opacity=0.5,
        showscale=False
    )
)

fig.show()

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names

In [31]:
# Regression plane visualization for Tv ad column or news one

#Create grid
x_tv = np.linspace(df['TV Ad Budget ($)'].min(), df['TV Ad Budget ($)'].max(), 30)
x_news = np.linspace(df['Newspaper Ad Budget ($)'].min(), df['Newspaper Ad Budget ($)'].max(), 30)

xGrid_tv, xGrid_news = np.meshgrid(x_tv, x_news)

# Calculate the mean of 'Newspaper Ad Budget ($)' to keep it constant for the 3D plane visualization
mean_radio = df['Radio Ad Budget ($)'].mean()

# Create a constant array for 'Newspaper Ad Budget ($)' with the mean value
xGrid_radio = np.full(xGrid_tv.shape, mean_radio)

# Combine the grids into a single array for prediction
final = np.vstack((xGrid_tv.ravel(), xGrid_news.ravel(), xGrid_radio.ravel())).T

z = lr.predict(final).reshape(30, 30)

# 3D Plot
fig = px.scatter_3d(
    df,
    x='TV Ad Budget ($)',
    y='Newspaper Ad Budget ($)',
    z='Sales ($)',
    opacity=0.8
)

fig.add_trace(
    go.Surface(
        x=x_tv,
        y=x_news,
        z=z,
        opacity=0.5,
        showscale=False
    )
)

fig.show()

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names

In [32]:
lr.coef_

array([0.04735257, 0.17323832, 0.00466519])

In [33]:
lr.intercept_

np.float64(3.0544520115813842)

In [ ]:
# β₀ = 3.05445       ← intercept
#β₁ = 0.04735       ← TV
#β₂ = 0.17324       ← Radio
#β₃ = 0.00467       ← Newspaper

In [34]:
# Regression plane visualization for Radio + Newspaper

# Create grid
x_radio = np.linspace(
    df['Radio Ad Budget ($)'].min(),
    df['Radio Ad Budget ($)'].max(),
    30
)

x_news = np.linspace(
    df['Newspaper Ad Budget ($)'].min(),
    df['Newspaper Ad Budget ($)'].max(),
    30
)

xGrid_radio, xGrid_news = np.meshgrid(x_radio, x_news)

# Keep TV constant at its mean
mean_tv = df['TV Ad Budget ($)'].mean()

xGrid_tv = np.full(xGrid_radio.shape, mean_tv)

# Combine the grids for prediction
final = np.vstack((
    xGrid_tv.ravel(),
    xGrid_radio.ravel(),
    xGrid_news.ravel()
)).T

# Predict Sales
z = lr.predict(final).reshape(30, 30)

# 3D Plot
fig = px.scatter_3d(
    df,
    x='Radio Ad Budget ($)',
    y='Newspaper Ad Budget ($)',
    z='Sales ($)',
    opacity=0.8
)

fig.add_trace(
    go.Surface(
        x=x_radio,
        y=x_news,
        z=z,
        opacity=0.5,
        showscale=False
    )
)

fig.show()

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names